# Edge Detection and Image Filtering

In [1]:
import numpy as np

### Convolution Functions and Operators

In [2]:
def pixel_convolution(image, mask, image_location):
    image_row, image_col = image_location
    mask_height, mask_width = mask.shape

    height_margin = mask_height // 2
    width_margin = mask_width // 2

    convolution_sum = 0

    for i, row in enumerate(range(-height_margin, height_margin + 1)):
        for j, col in enumerate(range(-width_margin, width_margin + 1)):
            convolution_sum += image[row + image_row, col + image_col] * mask[i, j]

    return convolution_sum

def image_convolution(image, mask):
    filtered_image = []

    mask_height, mask_width = mask.shape
    image_height, image_width = image.shape
    
    start_row = mask_height // 2
    start_col = mask_width // 2

    end_row = image_height - start_row
    end_col = image_width - start_col

    filtered_image = np.zeros((end_col - start_col, end_row - start_row))

    for i, row in enumerate(range(start_row, end_row)):
        for j, col in enumerate(range(start_col, end_col)):
            filtered_image[i, j] = pixel_convolution(image, mask, (row, col))
        
    return filtered_image

def gradient_direction(image, mask_x, mask_y):
    image_x_convolution = image_convolution(image, mask_x)
    image_y_convolution = image_convolution(image, mask_y)

    return np.arctan(image_y_convolution / image_x_convolution)

prewitt_x_operator = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

prewitt_y_operator = np.array([
    [1, 1, 1],
    [0, 0, 0],
    [-1, -1, -1]
])

sobel_x_operator = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])

sobel_y_operator = np.array([
    [1, 2, 1],
    [0, 0, 0],
    [-1, -2, -1]
])

laplacian_operator = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
])

def prewitt_gradient(image):
    return gradient_direction(image, prewitt_x_operator, prewitt_y_operator)

def sobel_gradient(image):
    return gradient_direction(image, sobel_x_operator, sobel_y_operator)

### Question 1: Calculate the gradient profile with different operators.

In [3]:
question_1_image = np.array([
    [3, 4, 8, 15, 25, 44, 50, 52],
    [3, 4, 8, 15, 25, 44, 50, 52],
    [3, 4, 8, 15, 25, 44, 50, 52],
    [3, 4, 8, 15, 25, 44, 50, 52],
    [3, 4, 8, 15, 25, 44, 50, 52],
    [3, 4, 8, 15, 25, 44, 50, 52],
    [3, 4, 8, 15, 25, 44, 50, 52],
    [3, 4, 8, 15, 25, 44, 50, 52]
])

#### Part(a): The Prewitt Operator

In [4]:
print(image_convolution(question_1_image, prewitt_x_operator))
print(image_convolution(question_1_image, prewitt_y_operator))

[[15. 33. 51. 87. 75. 24.]
 [15. 33. 51. 87. 75. 24.]
 [15. 33. 51. 87. 75. 24.]
 [15. 33. 51. 87. 75. 24.]
 [15. 33. 51. 87. 75. 24.]
 [15. 33. 51. 87. 75. 24.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### Part (b): The Sobel Operator

In [5]:
print(image_convolution(question_1_image, sobel_x_operator))
print(image_convolution(question_1_image, sobel_y_operator))

[[ 20.  44.  68. 116. 100.  32.]
 [ 20.  44.  68. 116. 100.  32.]
 [ 20.  44.  68. 116. 100.  32.]
 [ 20.  44.  68. 116. 100.  32.]
 [ 20.  44.  68. 116. 100.  32.]
 [ 20.  44.  68. 116. 100.  32.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### Part(c): The Laplacian Operator

In [6]:
print(image_convolution(question_1_image, laplacian_operator))

[[  3.   3.   3.   9. -13.  -4.]
 [  3.   3.   3.   9. -13.  -4.]
 [  3.   3.   3.   9. -13.  -4.]
 [  3.   3.   3.   9. -13.  -4.]
 [  3.   3.   3.   9. -13.  -4.]
 [  3.   3.   3.   9. -13.  -4.]]


### Question 2: Calculate the pixel gradients

In [7]:
question_2_image = np.array([
    [7, 12, 9],
    [6, 7, 8],
    [3, 4, 5]
])

#### Part (a): The Prewitt Operators

In [8]:
radian_angle = prewitt_gradient(question_2_image)
print(f"Gradient angle is {radian_angle[0, 0] * 180 / np.pi:.2f} degrees.")

Gradient angle is 69.44 degrees.


#### Part (b): The Sobel Operators

In [9]:
radian_angle = sobel_gradient(question_2_image)
print(f"Gradient angle is {radian_angle[0, 0] * 180 / np.pi:.2f} degrees.")

Gradient angle is 71.57 degrees.


### Question 3: Smoothing Convolution

In [10]:
smoothing_operator = np.array([
    [1/36, 1/9, 1/36],
    [1/9, 4/9, 1/9],
    [1/36, 1/9, 1/36]
])

print(image_convolution(question_1_image, smoothing_operator))

[[ 4.5         8.5        15.5        26.5        41.83333333 49.33333333]
 [ 4.5         8.5        15.5        26.5        41.83333333 49.33333333]
 [ 4.5         8.5        15.5        26.5        41.83333333 49.33333333]
 [ 4.5         8.5        15.5        26.5        41.83333333 49.33333333]
 [ 4.5         8.5        15.5        26.5        41.83333333 49.33333333]
 [ 4.5         8.5        15.5        26.5        41.83333333 49.33333333]]


Convolving the smoothing operator over the image from Question 1 spreads the intensities out to neighbouring pixels, creating a blurring effect. The determinant of the smoothing operator is 1, so unlike the other operators, this will not increase the overall brightness of the image.

The computational cost of this calculation is O(n^4), as for each pixel in the image (N x N pixels), the mask needs to be convolved over, which for a mask of row and column size K, is (K x K) computations per pixel. Therefore there are (N^2 x K^2) computations.

This can be reduced by applying two one-dimensional masks for each pixel, reducing the number of computations to (2 x N^2 x K), so the time complexity becomes O(n^3).